<?php
declare(strict_types=1);


namespace App\Model;


class ArticleModel extends \App\Core\CoreModel implements \App\Core\ModelInterface
{
    /**
     * @param string $sql
     * @param array $params
     * @param bool $all
     * @return mixed
     */
    public static function query(string $sql, array $params = [], bool $all = false): mixed
    {
        return parent::query($sql, $params, $all); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public static function all(): mixed
    {
        return parent::all(); // TODO: Change the autogenerated stub
    }

    /**
     * @param int $id
     * @return mixed
     */
    public static function find(int $id): mixed
    {
        return parent::find($id); // TODO: Change the autogenerated stub
    }

}

